### PR TITLE
Integrate resteasy-spring feature-pack 3.1.1.Beta1

### PR DESCRIPTION
**Pull request by jfdenise**

### CODE REVIEW

**Comment by liweinan** [comment]
Cool!

**Comment by liweinan** [comment]
@jamezp I guess this is the reason we need to keep the `resteast-spring` in-project feature pack modules, and we need to maintain the versions here, am I right? 

@jfdenise And this is galleon feature pack is needed to support the Glow layer detection of `resteasy-spring`, is my understanding correct?

**Comment by liweinan** [comment]
Here are the related PRs:

- https://github.com/wildfly/wildfly-glow/pull/21
- https://github.com/resteasy/resteasy-spring/pull/162

**Comment by jamezp** [comment]
@liweinan I don't really know what this project does TBH. We'll have to see what @jfdenise says. 

That said, the `org.jboss.resteasy.resteasy-spring` module is defined in the WildFly code base. If we want to make it a layer, we need to add it there.

**Comment by liweinan** [comment]
> @liweinan I don't really know what this project does TBH. We'll have to see what @jfdenise says.

Okay!

> 
> That said, the `org.jboss.resteasy.resteasy-spring` module is defined in the WildFly code base. 

The `resteasy-spring` version used in this PR is `3.1.1.Beta1`, so I thought it depends on the feature pack from `resteasy-spring` instead of wildfly codebase.

> If we want to make it a layer, we need to add it there.

Is there any example or code link that shows how this is implemented? (with my understanding, the layer definition must depend on a defined feature pack right?)

**Comment by jamezp** [comment]
> > That said, the `org.jboss.resteasy.resteasy-spring` module is defined in the WildFly code base.
> 
> The `resteasy-spring` version used in this PR is `3.1.1.Beta1`, so I thought it depends on the feature pack from `resteasy-spring` instead of wildfly codebase.

I think this is used for WildFly Glow, but I don't really know. I can say that the version is defined and used in WildFly https://github.com/wildfly/wildfly/blob/b3733d5afa710e9424fcf087b42960f6d1f13e04/pom.xml#L517.

> 
> > If we want to make it a layer, we need to add it there.
> 
> Is there any example or code link that shows how this is implemented? (with my understanding, the layer definition must depend on a defined feature pack right?)

You'd need to copy what is in the resteasy-spring feature pack into WildFly itself.

**Comment by liweinan** [comment]
@jfdenise In addition I have a question: Does Glow only detect layers not feature packs, which means if a feature pack doesn't have a `layer-spec.xml` then Glow can't scan to add the feature pack?

**Comment by jfdenise** [comment]
@liweinan , Glow detects layers and add feature-packs that contain the detected layers. if no layer defined, then the feature-pack is not usable with Glow.

**Comment by liweinan** [comment]
@jfdenise Thanks for teaching!

**Pull request merged**
